name: Continuous Integration

'on':
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  ci:
    name: Run the test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.2'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-versions }}'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHP CS Fixer
        run: composer install --prefer-dist --no-progress --working-dir=tools/php-cs-fixer

      - name: Run PHP CS Fixer
        run: composer lint-check

      - name: Install PHPStan
        run: composer install --prefer-dist --no-progress --working-dir=tools/phpstan

      - name: Run PHPStan
        run: composer phpstan

      - name: Run tests
        run: composer test
